//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taxi_Monitering
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AACPTMCSEntities : DbContext
    {
        public AACPTMCSEntities()
            : base("name=AACPTMCSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tbl_Attedance> tbl_Attedance { get; set; }
        public virtual DbSet<tbl_Department> tbl_Department { get; set; }
        public virtual DbSet<tbl_Driver> tbl_Driver { get; set; }
        public virtual DbSet<tbl_Employee> tbl_Employee { get; set; }
        public virtual DbSet<tbl_Role> tbl_Role { get; set; }
        public virtual DbSet<tbl_Route> tbl_Route { get; set; }
        public virtual DbSet<tbl_System_Account> tbl_System_Account { get; set; }
        public virtual DbSet<tbl_Tariff> tbl_Tariff { get; set; }
        public virtual DbSet<tbl_Taxi> tbl_Taxi { get; set; }
        public virtual DbSet<tbl_Taxi_Owner> tbl_Taxi_Owner { get; set; }
        public virtual DbSet<tbl_Taxi_user> tbl_Taxi_user { get; set; }
        public virtual DbSet<tbl_Zone> tbl_Zone { get; set; }
    }
}
