//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taxi_Monitering
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Route
    {
        public string Route_Id { get; set; }
        public string Route_Name { get; set; }
        public string Route_Description { get; set; }
        public string Route_Start { get; set; }
        public string Route_End { get; set; }
        public Nullable<decimal> Roue_Total_Distance { get; set; }
        public Nullable<System.DateTime> Route_Act_Date { get; set; }
        public string Zone_Id { get; set; }
        public string Tariff_Id { get; set; }
    
        public virtual tbl_Tariff tbl_Tariff { get; set; }
        public virtual tbl_Zone tbl_Zone { get; set; }
    }
}
