//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taxi_Monitering
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Driver
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Driver()
        {
            this.tbl_Taxi_Owner = new HashSet<tbl_Taxi_Owner>();
        }
    
        public string Driver_ID { get; set; }
        public string Driver_First_Name { get; set; }
        public string Driver_Last_Name { get; set; }
        public string Driver_lisence_No { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Taxi_Owner> tbl_Taxi_Owner { get; set; }
    }
}
