//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taxi_Monitering
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Taxi_user
    {
        public string id { get; set; }
        public string Commnet { get; set; }
        public string Taxi_ID { get; set; }
    
        public virtual tbl_Taxi tbl_Taxi { get; set; }
    }
}
