//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taxi_Monitering
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Taxi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Taxi()
        {
            this.tbl_Attedance = new HashSet<tbl_Attedance>();
            this.tbl_Taxi_user = new HashSet<tbl_Taxi_user>();
        }
    
        public string Taxi_ID { get; set; }
        public string Taxi_Code { get; set; }
        public Nullable<System.DateTime> Taxi_Manf_Year { get; set; }
        public string Taxi_Model { get; set; }
        public Nullable<decimal> Taxi_Licence_No { get; set; }
        public string Zone_Id { get; set; }
        public string Owr_Id { get; set; }
        public string Driver_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Attedance> tbl_Attedance { get; set; }
        public virtual tbl_Taxi_Owner tbl_Taxi_Owner { get; set; }
        public virtual tbl_Zone tbl_Zone { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Taxi_user> tbl_Taxi_user { get; set; }
    }
}
