//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taxi_Monitering
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Employee()
        {
            this.tbl_Attedance = new HashSet<tbl_Attedance>();
        }
    
        public string Emp_Id { get; set; }
        public string Emp_First_Name { get; set; }
        public string Emp_Last_name { get; set; }
        public Nullable<System.DateTime> Emp_Act_date { get; set; }
        public string Emp_Postion { get; set; }
        public string Department_ID { get; set; }
        public string Acc_ID { get; set; }
        public string Emp_Gender { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Attedance> tbl_Attedance { get; set; }
        public virtual tbl_Department tbl_Department { get; set; }
        public virtual tbl_System_Account tbl_System_Account { get; set; }
    }
}
