//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taxi_Monitering
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_Taxi_Owner
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Taxi_Owner()
        {
            this.tbl_Taxi = new HashSet<tbl_Taxi>();
        }
    
        public string Owr_Id { get; set; }
        public string Owr_First_Name { get; set; }
        public string Owr_Last_name { get; set; }
        public string Owr_Reg_city { get; set; }
        public Nullable<System.DateTime> Owr_Reg_date { get; set; }
        //[Required(ErrorMessage ="")]
        public string Owr_Gender { get; set; }
        public string Owr_Subcity { get; set; }
        public string Owr_Wereda { get; set; }
        public string Owr_House_NO { get; set; }
        public string Owr_PIN { get; set; }
        public string Driver_ID { get; set; }
    
        public virtual tbl_Driver tbl_Driver { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Taxi> tbl_Taxi { get; set; }
    }
}
